### ISSUE TITLE
多语言储存格式。

### ISSUE THREAD

**Issue by al-wei** [Giant-Salted-Fish/Hide-Key-Binding#1]
**Is your feature request related to a problem? Please describe.**

    S:hide_key_bindings <
多语言。

![image](https://github.com/user-attachments/assets/3470e646-cffb-4bb3-a429-3d80f2596cdc)

当我们将语言设置为非英文，那么键也是非英文储存。但是如果英语玩家使用了modpack那么那些非英文键还有效吗？

那么我们可以统一性的储存英文的键吗？而不是当前选择语言如汉语。

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by al-wei** [comment]
这个问题在我向您推荐的 rebind mod中也有。
![image](https://github.com/user-attachments/assets/0f426791-9d6e-4add-944c-291e1efb6f64)

我的解决方法是我自己写了一遍英文。但这不现实。普通玩家可能无法获取其它语言的键，并且世界上有那么多语言，一个整合包作者不可能包括所有。

**Comment by al-wei** [comment]
这个问题在DKS中也有
![image](https://github.com/user-attachments/assets/d4f7d531-6ab2-4ada-b6e0-5d61441a42e3)

**Comment by al-wei** [comment]
我很难判断如果切换成其它语言键是否有效。

**Comment by Giant-Salted-Fish** [comment]
HKB 的代码中并没有尝试储存本地化后的按键名名称。如果配置文件中出现的了中文或其他语言的名称，那大概率是这个模组 `KeyBinding#getKeyDescription()` 的实现有问题。你可以提供下有类似问题的模组名称，以便我这边进行查证。

**Comment by al-wei** [comment]
我的测试答案是切换语言，前语言无效。
这涉及到，KBP，DKS，HKB，除此之外defaultoptions这种模组也是会有汉语等非英语储存。

![image](https://github.com/user-attachments/assets/33f28551-b999-4cd7-abd4-c35479699666)

这种模组的话，像是
https://www.mcmod.cn/class/11066.html
https://www.mcmod.cn/class/11936.html
（打开配置，缩放就是这个模组里的）
https://www.mcmod.cn/class/5444.html
等模组安装时有，这种模组还是有些多的。

**Comment by al-wei** [comment]
如果可以的话，出一个储存固定语言的比如英文的设定就可以解决了。

**Comment by Giant-Salted-Fish** [comment]
我查看了相关模组的代码实现，它们的问题在于错误地使用了 `KeyBinding` 的构造函数，比如 [Valkyrie 模组](https://github.com/Red-Studio-Ragnarok/Valkyrie/blob/8f991badb56983ac7c76b4cf9feeb3c8c10ae0e1/src/main/java/dev/redstudio/valkyrie/keys/KeyBindings.java#L17) 和 [Classy Hats 模组](https://github.com/yrsegal/ClassyHats/blob/59b96ffd7e89a241be646af3ccd55a65ba8b3680/src/main/java/wiresegal/classyhats/client/keybind/KeyBindHandler.kt#L12)，而 Fancier Block Particles 本身就没有中文支持（zh_cn.lang 文件缺失）。

这些问题的成因不在于 HKB/DKS/KBP 模组本身，亦不在其能解决的能力范围之内。实际上，你不能指望任何其它按键增强模组有能力帮它们擦屁股。要解决这些问题你需要给这些有问题的模组提 Issue 请求他们修复问题。如果对应模组已经年久失修无人维护，那就只能忍受这些问题或是寻找替代，当然如果你有钞能力也可以选择雇人接手相关模组的维护修复这些问题。总之，这不是 HKB/DKS/KBP 能够/应该解决的问题。

**Comment by Giant-Salted-Fish** [comment]
理想中我们是完美主义者，现实中我们不得不面对 **时间-金钱-质量** 的不可能三角。使用现成的模组制作整合包节约了时间，代价就是需要牺牲细节（质量），或者花费时间（自己修复错误）/金钱（找人修复错误）来弥补。

**Comment by al-wei** [comment]
明白

**Comment by Giant-Salted-Fish** [comment]
祝愿你能完成符合自己预期的整合包。

**Comment by al-wei** [comment]
好的，再见。
